onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - "@vercel/speed-insights"
  - bcrypt
  - bufferutil
  - core-js-pure
  - cypress
  - esbuild
  - prisma
  - sharp
  - utf-8-validate
