name: Publish to Instagram

on:
  schedule:
    - cron: "15 0,12,15,18,21 * * *"
    # - cron: "0 0 1 1 0"

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Publish to Instagram
        run: |
          curl --request POST \
          --url 'https://tech-news.bocono-labs.com/api/instagram' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'
