name: Process News

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the News from the Brave Search API
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/news/pull' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'

  parse:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: Parse the News using Readability
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/news/parse' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'

  embed:
    runs-on: ubuntu-latest
    needs: parse
    steps:
      - name: Generate Embedings for the News
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/news/embed' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'
