name: Generate Publication

on:
  schedule:
    - cron: "*/30 13-23,0,1 * * *"

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the publication from a new
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/publication/generate' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'
