name: Generate Publication

on:
  schedule:
    - cron: "*/30 15-23,0,1 * * *"

jobs:
  blog:
    runs-on: self-hosted
    steps:
      - name: Generate the publication from a new
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/publication/generate' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'

  twitter:
    runs-on: self-hosted
    needs: blog
    steps:
      - name: Generate a twitter post from an article
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/publication/twitter' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'

  linkedin:
    runs-on: self-hosted
    needs: blog
    steps:
      - name: Generate a twitter post from an article
        run: |
          curl --request POST \
          --url 'https://news.bocono-labs.com/api/publication/linkedin' \
          --header 'x-api-key: ${{ secrets.API_KEY }}'
